spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  application:
    name: example
  liquibase:
    change-log: classpath:/db/master.xml
server:
  port: ${SERVER_HTTP_PORT:8085}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs